<?php

if (!defined('ABSPATH')) {
    exit;
}

class Ruplin_Favicon_Manager {
    
    /**
     * Initialize the favicon manager
     */
    public function __construct() {
        // Hook into wp_head to inject favicon
        add_action('wp_head', array($this, 'inject_favicon'), 1);
        
        // Add AJAX handlers for favicon upload
        add_action('wp_ajax_upload_favicon', array($this, 'handle_favicon_upload'));
        add_action('wp_ajax_remove_favicon', array($this, 'handle_favicon_removal'));
        
        // Ensure upload directory exists
        add_action('init', array($this, 'ensure_upload_directory'));
    }
    
    /**
     * Inject favicon into head if one is set
     */
    public function inject_favicon() {
        $favicon_url = get_option('ruplin_favicon_url', '');
        
        if (!empty($favicon_url)) {
            echo "\n<!-- Favicon - Generated by Ruplin Favicon Manager -->\n";
            
            // Get file extension to determine favicon type
            $file_extension = strtolower(pathinfo($favicon_url, PATHINFO_EXTENSION));
            
            if ($file_extension === 'ico') {
                // Traditional ICO favicon
                echo '<link rel="shortcut icon" href="' . esc_url($favicon_url) . '" type="image/x-icon">' . "\n";
                echo '<link rel="icon" href="' . esc_url($favicon_url) . '" type="image/x-icon">' . "\n";
            } elseif (in_array($file_extension, array('png', 'jpg', 'jpeg', 'gif', 'svg'))) {
                // Modern image formats
                $mime_type = $this->get_mime_type($file_extension);
                echo '<link rel="icon" href="' . esc_url($favicon_url) . '" type="' . $mime_type . '">' . "\n";
                
                // Add sizes for PNG (common for modern favicons)
                if ($file_extension === 'png') {
                    echo '<link rel="icon" sizes="32x32" href="' . esc_url($favicon_url) . '" type="image/png">' . "\n";
                    echo '<link rel="icon" sizes="16x16" href="' . esc_url($favicon_url) . '" type="image/png">' . "\n";
                }
            }
            
            // Apple touch icon (for mobile devices)
            if (in_array($file_extension, array('png', 'jpg', 'jpeg'))) {
                echo '<link rel="apple-touch-icon" href="' . esc_url($favicon_url) . '">' . "\n";
            }
        }
    }
    
    /**
     * Handle favicon upload via AJAX
     */
    public function handle_favicon_upload() {
        // Check nonce
        if (!isset($_POST['nonce']) || !wp_verify_nonce($_POST['nonce'], 'favicon_upload_nonce')) {
            wp_send_json_error('Invalid nonce');
            return;
        }
        
        // Check permissions
        if (!current_user_can('manage_options')) {
            wp_send_json_error('Insufficient permissions');
            return;
        }
        
        // Check if file was uploaded
        if (!isset($_FILES['favicon_file']) || $_FILES['favicon_file']['error'] !== UPLOAD_ERR_OK) {
            wp_send_json_error('No file uploaded or upload error');
            return;
        }
        
        $file = $_FILES['favicon_file'];
        
        // Validate file type
        $allowed_types = array('image/x-icon', 'image/vnd.microsoft.icon', 'image/png', 'image/jpeg', 'image/jpg', 'image/gif', 'image/svg+xml');
        $file_type = wp_check_filetype($file['name']);
        
        if (!in_array($file['type'], $allowed_types) && !in_array($file_type['type'], $allowed_types)) {
            wp_send_json_error('Invalid file type. Please upload ICO, PNG, JPG, GIF, or SVG files only.');
            return;
        }
        
        // Validate file size (max 2MB)
        if ($file['size'] > 2 * 1024 * 1024) {
            wp_send_json_error('File too large. Maximum size is 2MB.');
            return;
        }
        
        // Create upload directory
        $upload_dir = $this->get_upload_directory();
        if (!$upload_dir) {
            wp_send_json_error('Could not create upload directory');
            return;
        }
        
        // Remove old favicon if exists
        $this->remove_existing_favicon();
        
        // Generate unique filename
        $file_extension = pathinfo($file['name'], PATHINFO_EXTENSION);
        $filename = 'favicon_' . time() . '.' . $file_extension;
        $file_path = $upload_dir['path'] . '/' . $filename;
        
        // Move uploaded file
        if (move_uploaded_file($file['tmp_name'], $file_path)) {
            $file_url = $upload_dir['url'] . '/' . $filename;
            
            // Save favicon URL in options
            update_option('ruplin_favicon_url', $file_url);
            update_option('ruplin_favicon_path', $file_path);
            
            wp_send_json_success(array(
                'message' => 'Favicon uploaded successfully',
                'favicon_url' => $file_url
            ));
        } else {
            wp_send_json_error('Failed to move uploaded file');
        }
    }
    
    /**
     * Handle favicon removal via AJAX
     */
    public function handle_favicon_removal() {
        // Check nonce
        if (!isset($_POST['nonce']) || !wp_verify_nonce($_POST['nonce'], 'favicon_remove_nonce')) {
            wp_send_json_error('Invalid nonce');
            return;
        }
        
        // Check permissions
        if (!current_user_can('manage_options')) {
            wp_send_json_error('Insufficient permissions');
            return;
        }
        
        $this->remove_existing_favicon();
        
        wp_send_json_success(array(
            'message' => 'Favicon removed successfully'
        ));
    }
    
    /**
     * Remove existing favicon file and options
     */
    private function remove_existing_favicon() {
        $favicon_path = get_option('ruplin_favicon_path', '');
        
        if (!empty($favicon_path) && file_exists($favicon_path)) {
            unlink($favicon_path);
        }
        
        delete_option('ruplin_favicon_url');
        delete_option('ruplin_favicon_path');
    }
    
    /**
     * Get upload directory for favicons
     */
    private function get_upload_directory() {
        $upload_dir = wp_upload_dir();
        $favicon_dir = $upload_dir['basedir'] . '/ruplin-favicons';
        $favicon_url = $upload_dir['baseurl'] . '/ruplin-favicons';
        
        if (!file_exists($favicon_dir)) {
            if (!wp_mkdir_p($favicon_dir)) {
                return false;
            }
        }
        
        return array(
            'path' => $favicon_dir,
            'url' => $favicon_url
        );
    }
    
    /**
     * Ensure upload directory exists on init
     */
    public function ensure_upload_directory() {
        $this->get_upload_directory();
    }
    
    /**
     * Get MIME type for file extension
     */
    private function get_mime_type($extension) {
        $mime_types = array(
            'ico' => 'image/x-icon',
            'png' => 'image/png',
            'jpg' => 'image/jpeg',
            'jpeg' => 'image/jpeg',
            'gif' => 'image/gif',
            'svg' => 'image/svg+xml'
        );
        
        return isset($mime_types[$extension]) ? $mime_types[$extension] : 'image/x-icon';
    }
}

// Initialize the favicon manager
new Ruplin_Favicon_Manager();