<?php

if (!defined('ABSPATH')) {
    exit;
}

class Ruplin_Schema_Generator {
    
    /**
     * Initialize the schema generator
     */
    public function __construct() {
        // Hook into wp_head to inject schema when enabled
        add_action('wp_head', array($this, 'maybe_inject_schema'), 1);
    }
    
    /**
     * Check if schema injection is enabled and inject if true
     */
    public function maybe_inject_schema() {
        // Check if schema injection is enabled
        $inject_enabled = get_option('ruplin_inject_schema_enabled', false);
        
        if (!$inject_enabled) {
            return;
        }
        
        // Generate and output the schema
        $schema = $this->generate_schema();
        if (!empty($schema)) {
            echo "\n<!-- Structured Data for Local Business - Generated by Ruplin -->\n";
            echo '<script type="application/ld+json">' . "\n";
            echo $schema;
            echo "\n</script>\n";
        }
    }
    
    /**
     * Generate the complete schema markup
     */
    private function generate_schema() {
        global $wpdb;
        
        // Get business data from zen_sitespren table
        $sitespren_table = $wpdb->prefix . 'zen_sitespren';
        $business_data = $wpdb->get_row("SELECT * FROM $sitespren_table LIMIT 1");
        
        if (!$business_data) {
            return '';
        }
        
        // Get area served cities (location pages)
        $area_served = $this->get_area_served_cities();
        
        // Get services offered (service pages)
        $services_offered = $this->get_services_offered();
        
        // Format phone number if country code is 1
        $formatted_phone = $this->format_phone_number(
            $business_data->driggs_phone_1, 
            $business_data->driggs_phone_country_code
        );
        
        // Build the schema array
        $schema = array(
            '@context' => 'https://schema.org',
            '@type' => 'LocalBusiness',
            'name' => $this->get_field_value($business_data->driggs_brand_name),
            'description' => '', // Leave blank for now but display key
            'telephone' => $formatted_phone,
            'priceRange' => '', // Leave blank for now but display key
            'openingHours' => $this->get_field_value($business_data->driggs_hours_for_schema),
            'address' => array(
                '@type' => 'PostalAddress',
                'streetAddress' => $this->get_field_value($business_data->driggs_street_1),
                'addressLocality' => $this->get_field_value($business_data->driggs_city),
                'addressRegion' => $this->get_field_value($business_data->driggs_state_code),
                'postalCode' => $this->get_field_value($business_data->driggs_zip),
                'addressCountry' => $this->get_field_value($business_data->driggs_country, 'US')
            ),
            'geo' => array(
                '@type' => 'GeoCoordinates',
                'address' => $this->build_full_address($business_data)
            ),
            'serviceArea' => array(
                '@type' => 'GeoCircle',
                'geoRadius' => $this->get_field_value($business_data->georadius_for_schema),
                'geoMidpoint' => array(
                    '@type' => 'GeoCoordinates',
                    'address' => $this->build_full_address($business_data)
                )
            )
        );
        
        // Add area served if available
        if (!empty($area_served)) {
            $schema['areaServed'] = $area_served;
        }
        
        // Add services catalog if available
        if (!empty($services_offered)) {
            $schema['hasOfferCatalog'] = array(
                '@type' => 'OfferCatalog',
                'name' => 'Services',
                'itemListElement' => $services_offered
            );
        }
        
        // Add aggregate rating if available
        if (!empty($business_data->ratingvalue_for_schema) || !empty($business_data->reviewcount_for_schema)) {
            $schema['aggregateRating'] = array(
                '@type' => 'AggregateRating',
                'ratingValue' => $this->get_field_value($business_data->ratingvalue_for_schema, ''),
                'reviewCount' => $this->get_field_value($business_data->reviewcount_for_schema, '')
            );
        }
        
        // Convert to JSON with pretty printing
        return json_encode($schema, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
    }
    
    /**
     * Get area served cities from location pages
     */
    private function get_area_served_cities() {
        global $wpdb;
        
        $pylons_table = $wpdb->prefix . 'pylons';
        $posts_table = $wpdb->prefix . 'posts';
        $sitespren_table = $wpdb->prefix . 'zen_sitespren';
        
        // Get the main city from business data
        $business_data = $wpdb->get_row("SELECT driggs_city FROM $sitespren_table LIMIT 1");
        $main_city = $business_data ? $business_data->driggs_city : '';
        
        // Query for location pages
        $query = "
            SELECT DISTINCT p.locpage_neighborhood
            FROM $pylons_table p
            JOIN $posts_table wp ON p.rel_wp_post_id = wp.ID
            WHERE wp.post_status = 'publish'
            AND p.pylon_archetype = 'locationpage'
            AND p.locpage_neighborhood IS NOT NULL
            AND p.locpage_neighborhood != ''
            ORDER BY p.locpage_neighborhood
        ";
        
        $neighborhoods = $wpdb->get_col($query);
        
        if (empty($neighborhoods)) {
            return array();
        }
        
        // Build area served array
        $area_served = array();
        foreach ($neighborhoods as $neighborhood) {
            $area_served[] = array(
                '@type' => 'City',
                'name' => $neighborhood,
                'containedInPlace' => array(
                    '@type' => 'City',
                    'name' => $main_city
                )
            );
        }
        
        return $area_served;
    }
    
    /**
     * Get services offered from service pages
     */
    private function get_services_offered() {
        global $wpdb;
        
        $pylons_table = $wpdb->prefix . 'pylons';
        $posts_table = $wpdb->prefix . 'posts';
        $sitespren_table = $wpdb->prefix . 'zen_sitespren';
        
        // Get business data for service details
        $business_data = $wpdb->get_row("SELECT * FROM $sitespren_table LIMIT 1");
        if (!$business_data) {
            return array();
        }
        
        $business_name = $this->get_field_value($business_data->driggs_brand_name);
        $business_category = $this->get_field_value($business_data->driggs_industry);
        $city = $this->get_field_value($business_data->driggs_city);
        $full_address = $this->build_full_address($business_data);
        
        // Query for service pages
        $query = "
            SELECT DISTINCT p.moniker
            FROM $pylons_table p
            JOIN $posts_table wp ON p.rel_wp_post_id = wp.ID
            WHERE wp.post_status = 'publish'
            AND p.pylon_archetype = 'servicepage'
            AND p.locpage_neighborhood IS NOT NULL
            AND p.moniker IS NOT NULL
            AND p.moniker != ''
            ORDER BY p.moniker
        ";
        
        $services = $wpdb->get_col($query);
        
        if (empty($services)) {
            return array();
        }
        
        // Build services array
        $services_offered = array();
        foreach ($services as $service) {
            $services_offered[] = array(
                '@type' => 'Offer',
                'name' => $service,
                'category' => $business_category,
                'areaServed' => $city,
                'availableAtOrFrom' => array(
                    '@type' => 'Place',
                    'name' => $business_name,
                    'address' => $full_address
                )
            );
        }
        
        return $services_offered;
    }
    
    /**
     * Build full address string
     */
    private function build_full_address($business_data) {
        $parts = array();
        
        if (!empty($business_data->driggs_street_1)) {
            $parts[] = $business_data->driggs_street_1;
        }
        if (!empty($business_data->driggs_city)) {
            $parts[] = $business_data->driggs_city;
        }
        if (!empty($business_data->driggs_state_code)) {
            $parts[] = $business_data->driggs_state_code;
        }
        if (!empty($business_data->driggs_zip)) {
            $parts[] = $business_data->driggs_zip;
        }
        
        return implode(', ', $parts);
    }
    
    /**
     * Get field value with fallback
     */
    private function get_field_value($value, $default = '') {
        return !empty($value) ? $value : $default;
    }
    
    /**
     * Format phone number based on country code
     * If country code is 1, format as (xxx) xxx-xxxx
     * Otherwise, return the phone number as-is
     */
    private function format_phone_number($phone, $country_code) {
        // Check if phone exists
        if (empty($phone)) {
            return '';
        }
        
        // If country code is 1, apply US/Canada formatting
        if ($country_code == '1' || $country_code == 1) {
            // Remove any non-numeric characters first
            $phone_clean = preg_replace('/[^0-9]/', '', $phone);
            
            // Check if we have exactly 10 digits
            if (strlen($phone_clean) == 10) {
                // Format as (xxx) xxx-xxxx
                return sprintf(
                    '(%s) %s-%s',
                    substr($phone_clean, 0, 3),  // Area code
                    substr($phone_clean, 3, 3),  // First 3 digits
                    substr($phone_clean, 6, 4)   // Last 4 digits
                );
            }
        }
        
        // Return phone as-is if not country code 1 or not 10 digits
        return $phone;
    }
}

// Initialize the schema generator
new Ruplin_Schema_Generator();